# This is a basic workflow to help you get started with Actions

name: release-bot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - name: Setting up git
      run: |
        git config --global user.name 'Release bot'
        git config --global user.email 'lev_135@mail.ru'
        git fetch
        git checkout $GITHUB_HEAD_REF

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies
    - name: Build
      run: cabal build texgen -O2
    - name: Move binary
      run: |
        for file in $(find . -name "texgen*" -type f)
        do
          echo $file
          dir="$(dirname $file)"
          if [[ "$dir" == *build/texgen ]]
          then
            echo "build found: $file"
            mkdir -p ./bin
            mv $file ./bin
          fi
        done
    - name: Make release note
      run: |
        echo "$(date +"%Y-%m-%d %T"): on branch $GITHUB_HEAD_REF" >> bin/release-notes.txt
    - name: Commiting changes
      run: |
        git add -A
        git commit -m "Release on branch $GITHUB_HEAD_REF generated"
        git push
